### ISSUE TITLE
Sketch uses 1351530 bytes (103%)

### ISSUE THREAD

**Issue by rossedward** [tanakamasayuki/LinxESP32#3]
Trying to use the   LinxSerialConnection.Start(LinxDevice, 0); (USB Serial of ESP32)  with the whole code below:
There's an compilation error: 

> Sketch uses 1351530 bytes (103%) of program storage space. Maximum is 1310720 bytes.
text section exceeds available space in board

> Global variables use 52756 bytes (16%) of dynamic memory, leaving 274924 bytes for local variables. Maximum is 327680 bytes. Sketch too big;

Board Config:
> ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz(WIFI BT), QIO, 80MHz, 4MB (32MB), 921600, None

Arduino sketch:
```
#include <LinxESP32.h>

LinxESP32* LinxDevice;

void setup()
{
  LinxDevice = new LinxESP32();
  LinxSerialConnection.Start(LinxDevice, 0);
}

void loop()
{
  LinxSerialConnection.CheckForCommands();
  delay(1);
}
```

**Comment by tanakamasayuki** [comment]
![image](https://user-images.githubusercontent.com/10301363/139021857-686279a0-24aa-40c6-b989-f552d6440f04.png)

Hi. Expand the program area.
No OTA or Minimal SPIFFS

**Comment by rossedward** [comment]
Thank you!

Regards,
Ross
